global_frame: map
robot_frame: base_footprint
robot_base_frame: base_link

mesh_part: mesh
layers:
  - name: 'height_diff'
    type: 'mesh_layers/HeightDiffLayer'
  - name: 'roughness'
    type: 'mesh_layers/RoughnessLayer'
#  - name: 'inflation'
#    type: 'mesh_layers/InflationLayer'

height_diff:
  factor: 1.0
  threshold: 0.1

roughness:
  factor: 1.0
  threshold: 0.6

inflation:
  factor: 1.0
  inflation_radius: 0.5
  inscribed_radius: 0.10
  #inflation_radius: 1.0
  #inscribed_radius: 0.05
  lethal_value: 6
  inscribed_value: 4

