global_frame: map
robot_frame: base_footprint
robot_base_frame: base_link

mesh_part: mesh
layers:
  - name: 'height_diff'
    type: 'mesh_layers/HeightDiffLayer'
  - name: 'steepness'
    type: 'mesh_layers/SteepnessLayer'
    #  - name: 'inflation'
    #    type: 'mesh_layers/InflationLayer'

height_diff:
  factor: 0.7
  threshold: 0.7
  radius: 0.0

steepness:
  factor: 1.0
  threshold: 0.3

inflation:
  factor: 1.0
  inflation_radius: 1.0
  inscribed_radius: 0.3
  lethal_value: 1
  inscribed_value: 0.1

